#!/bin/bash
cd /opt/TuxCut

cmd = ""
if command -v gksudo >/dev/null 2>&1 ; then
	cmd="gksudo"
elif command -v kdesudo >/dev/null 2>&1 ; then 
	cmd="kdesudo"
elif command -v gksu >/dev/null 2>&1 ; then 
	cmd="gksu"
elif command -v kdesu >/dev/null 2>&1 ; then 
	cmd="kdesu"
elif command -v beesu >/dev/null 2>&1 ; then 
	cmd="beesu"
elif command -v sudo >/dev/null 2>&1 ; then 
	cmd="sudo"
fi

$cmd python /opt/TuxCut/tuxcut.py
